---
- hosts: localhostengine-nginx
  become: yes
  gather_facts: False
  tasks:

  - name: Install EPEL-release
    yum: name=epel-release state=present
  - name: connection
    command: ls -la 
    
  - name: connection
    command: kube set image deployment/saikiran786/node
